spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://121.4.111.87:3306/grainmarket_pms?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver

# 告诉 MyBatis Plus SQL 映射文件的位置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto # 主键自增

server:
  port: 10000