spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.cn.bing.com
          predicates:
            - Query=url, bing

        - id: qq_route
          uri: https://www.qq.com
          predicates:
              - Query=url, qq